name: CI
on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Fix permissions
        run: chmod +x gradlew
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Check formatting
        run: ./gradlew spotlessCheck

      - name: Run linters
        run: ./gradlew ktlintCheck detekt

      - name: Run tests
        run: ./gradlew test

      - name: Run compile and assembly
        run: ./gradlew assemble

      - name: Run full build
        run: ./gradlew clean build